version: "2"

services:
  web:
    image: arizawan/timestrap
    #build: .
    command: daphne timestrap.asgi:application --port 80 --bind 0.0.0.0 -v2
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=timestrap.settings.docker
      - SECRET_KEY=thunder.32
      - DB_USER=timesadmin
      - DB_PASS=nomog0987g
    depends_on:
      - db
      - redis

  db:
    image: postgres
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_USER=timesadmin
      - POSTGRES_PASSWORD=nomog0987g
      - PGDATA=/db-data
    volumes:
      - db:/db-data

  redis:
    image: redis

volumes:
  db:
