version: "2"

services:
  web:
    image: arizawan/timestrap
    #build: .
    command: daphne timestrap.asgi:application --port 80 --bind 0.0.0.0 -v2
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=timestrap.settings.docker
      - SECRET_KEY=thunder.32
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/db-data
    volumes:
      - db:/db-data

  redis:
    image: redis

volumes:
  db:
